# thanks to Brian Annis [https://github.com/brianannis] for proving the value
---
- hosts: macmine
  gather_facts: yes
  connection: local

  vars_files:
    - config.default.yml

  # override default configs
  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.local.yml"
      tags: ["always"]

  tasks:
  - name: create dev folder
    file:
      path: "{{ ansible_env.HOME }}/dev"
      owner: "{{ ansible_env.USER }}"
      mode: '0755'
      state: directory

  - homebrew_tap:
      name: wallix/awless
      state: present

  - name: brew taps
    homebrew:
      name: "{{ my_brews }}"
      state: present
      update_homebrew: yes
      upgrade_all: yes
    tags: ["homebrew", "brews"]

  - name: brew cask taps
    homebrew_cask:
      name: "{{ my_casks }}"
      state: present
      update_homebrew: yes
    tags: ["homebrew", "casks"]


  roles:
    - bash-profile-on-osx
      # using Docker for Mac (Nov 2017)
      # - docker-on-osx
      # - kubernetes-on-osx
      # - chef-ops
    - go-on-osx
    - python-on-osx
    - ssh-on-osx

