# credit to Brian Annis for paving the path
---
- hosts: localhost
  gather_facts: yes
  connection: local

  tasks:
  - name: install taps with homebrew
    homebrew:
      name: "{{ item }}"
      state: present
      update_homebrew: yes
      upgrade_all: yes
    with_items:
      - awscli
      - consul
      - docker-machine
      - docker-machine-driver-xhyve
      - git
      - go
      - graphviz
      - kops
      - kubernetes-cli
      - kubernetes-helm
      - ocaml
      - opam
      - python
      - python3
      - shellcheck
      - terraform
      - vagrant-completion
      - vault

  - name: install taps with homebrew casks
    homebrew_cask:
      name: "{{ item }}"
      state: present
      update_homebrew: yes
    with_items:
      - calibre
      - colloquy
      - dropbox
      - encryptr
      - firefox
      - google-chrome
      - iterm2
      - kindle
      - libreoffice
      - mactex
      - macvim
      # - menumeters
      - minikube
      - slack
      - sourcetree
      - textmate
      - vagrant
      - virtualbox
      - vlc
      #- yujitach-menumeters


# Create ssh keys

  - name: add .ssh dir
    file:
      path: ~/.ssh
      state: directory
      mode: 0700

  - name: add new schoology ssh key
    shell: ssh-keygen -b 4096 -t rsa -f ~/.ssh/id_rsa -q -N ""
    args:
      creates: ~/.ssh/id_rsa

  - name: add new personal ssh key
    shell: ssh-keygen -b 4096 -t rsa -f ~/.ssh/personal_id_rsa -q -N ""
    args:
      creates: ~/.ssh/personal_id_rsa

# Ferify standard dev env
  - name: add dev dir
    file:
      path: ~/dev
      state: directory
      mode: 0755
