# thanks to Brian Annis [https://github.com/brianannis] for proving the value
---
- hosts: macmine
  gather_facts: yes
  connection: local

  tasks:
  - name: install taps with homebrew
    homebrew:
      name: "{{ item }}"
      state: present
      update_homebrew: yes
      upgrade_all: yes
    with_items:
      - awscli
      - consul
      - git
      - go
      - graphviz
      - openvpn
      - python
      - python3
      - shellcheck
      - terraform
      - vagrant-completion
      - vault

  - name: install taps with homebrew casks
    homebrew_cask:
      name: "{{ item }}"
      state: present
      update_homebrew: yes
    with_items:
      - calibre
      - colloquy
      - dropbox
      - encryptr
      - firefox
      - google-chrome
      - iterm2
      - kindle
      - libreoffice
      - mactex
      - macvim
      - slack
      - sourcetree
      - textmate
      - vagrant
      - vlc
      ## optional taps
      # - menumeters
      #- virtualbox
      #- yujitach-menumeters


# Create ssh keys

  - name: add .ssh dir
    file:
      path: ~/.ssh
      state: directory
      mode: 0700

  - name: add new schoology ssh key
    shell: ssh-keygen -b 4096 -t rsa -f ~/.ssh/id_rsa -q -N ""
    args:
      creates: ~/.ssh/id_rsa

  - name: add new personal ssh key
    shell: ssh-keygen -b 4096 -t rsa -f ~/.ssh/personal_id_rsa -q -N ""
    args:
      creates: ~/.ssh/personal_id_rsa

# Ferify standard dev env
  - name: add dev dir
    file:
      path: ~/dev
      state: directory
      mode: 0755

  roles:
    - bash-profile-on-osx
    - docker-on-osx
    - kubernetes-on-osx

