# thanks to Brian Annis [https://github.com/brianannis] for proving the value
---
- hosts: macmine
  gather_facts: yes
  connection: local

  tasks:
  - homebrew_tap:
      name: wallix/awless
      state: present

  - name: brew taps
    homebrew:
      name: "{{ item }}"
      state: present
      update_homebrew: yes
      upgrade_all: yes
    with_items:
      - awscli
      - awless
      - consul
      - git
      - go
      - graphviz
      - jq
      - lua
      - luajit
      - macvim
      - openvpn
      - python
      - python3
      - shellcheck
      - terraform
      - tree
      - vagrant-completion
      - vault

  - name: brew cask taps
    homebrew_cask:
      name: "{{ item }}"
      state: present
      update_homebrew: yes
    with_items:
      - amazon-music
      - calibre
      - colloquy
      - dropbox
      - encryptr
      - firefox
      - google-chrome
      - hipchat
      - iterm2
      - kindle
      - libreoffice
      - mactex
      - slack
      - sourcetree
      - textmate
      - vagrant
      - virtualbox
      - vlc
      ## optional taps
      #- menumeters
      #- yujitach-menumeters


# Create ssh keys

  - name: add .ssh dir
    file:
      path: ~/.ssh
      state: directory
      mode: 0700

  - name: add new default ssh key
    shell: ssh-keygen -b 4096 -t rsa -f ~/.ssh/id_rsa -q -N ""
    args:
      creates: ~/.ssh/id_rsa

  - name: add new personal ssh key
    shell: ssh-keygen -b 4096 -t rsa -f ~/.ssh/personal_id_rsa -q -N ""
    args:
      creates: ~/.ssh/personal_id_rsa

# Ferify standard dev env
  - name: add dev dir
    file:
      path: ~/dev
      state: directory
      mode: 0755

  roles:
    - bash-profile-on-osx
      # using Docker for Mac (Nov 2017)
      # - docker-on-osx
    - kubernetes-on-osx
    - chef-ops

