# thanks to Brian Annis [https://github.com/brianannis] for proving the value
---
- hosts: macmine
  gather_facts: yes
  connection: local

  tasks:
  - name: create dev folder
    file:
      path: "{{ ansible_env.HOME }}/dev"
      owner: "{{ ansible_env.USER }}"
      mode: '0755'
      state: directory

  - homebrew_tap:
      name: wallix/awless
      state: present

  - name: brew taps
    homebrew:
      name: "{{ item }}"
      state: present
      update_homebrew: yes
      upgrade_all: yes
    with_items:
      - awscli
      - awless
      - bash-completion
      - consul
      - dos2unix
      - git
      - gnuplot
      - graphviz
      - gron
      - htop
      - jq
      - lua
      - luajit
      - macvim
      - mas
      - openvpn
      - packer
      - ruby
      - shellcheck
      - terraform
      - tree
      - vagrant-completion
      - vault

  - name: brew cask taps
    homebrew_cask:
      name: "{{ item }}"
      state: present
      update_homebrew: yes
    with_items:
      - amazon-music
      - calibre
      - colloquy
      - diffmerge
      - dropbox
      - encryptr
      - firefox
      - fluid
      - google-chrome
      - iterm2
      - java8
      - kindle
      - libreoffice
      - mactex
      - nightingale
      - racket
      - slack
      - sourcetree
      - spotify
      - textmate
      - vagrant
        #- virtualbox
        #- visual-studio-code
      - vlc
      ## optional taps
      #- malwarebytes
      #- menumeters
      #- yujitach-menumeters

  roles:
    - bash-profile-on-osx
      # using Docker for Mac (Nov 2017)
      # - docker-on-osx
    - kubernetes-on-osx
      #- chef-ops
    - go-on-osx
    - python-on-osx
    - ssh-on-osx

