# thanks to Brian Annis [https://github.com/brianannis] for proving the value
---
- hosts: macmine
  gather_facts: yes
  connection: local

  vars_files:
    - default_config.yml

  tasks:
  - name: create dev folder
    file:
      path: "{{ ansible_env.HOME }}/dev"
      owner: "{{ ansible_env.USER }}"
      mode: '0755'
      state: directory

  - homebrew_tap:
      name: wallix/awless
      state: present

  - name: brew taps
    homebrew:
      name: "{{ homebrew_taps }}"
      state: present
      update_homebrew: '{{ configure.update_homebrew }}'
      upgrade_all: '{{ configure.upgrade_all_taps }}'

  - name: brew cask taps
    homebrew_cask:
      name: "{{ homebrew_cask_taps }}"
      state: present
      update_homebrew: '{{ configure.update_homebrew }}'
      upgrade_all: '{{ configure.upgrade_all_cask_taps }}'

  roles:
    - bash-profile-on-osx
    # using Docker for Mac (Nov 2017)
    # - docker-on-osx
    #- kubernetes-on-osx
    #- chef-ops
    - go-on-osx
    - python-on-osx
    - ssh-on-osx

