---

  - name: install node.js repo
    apt_repository:
      repo: deb https://deb.nodesource.com/node_10.x trusty main
      state: present

  - name: install node.js repo
    apt_repository:
      repo: deb-src https://deb.nodesource.com/node_10.x trusty main
      state: present

  - name: install node.js
    apt:
      update_cache: yes
      name: nodejs

  - name: install node.js repo key
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present
