---
  - name: install taps with homebrew
    homebrew:
      name: "{{ item }}"
      state: present
    with_items:
      - kops
      - kubernetes-cli
      - kubernetes-helm

  - name: install taps with homebrew casks
    homebrew_cask:
      name: "{{ item }}"
      state: present
      update_homebrew: yes
    with_items:
      - minikube
