---
- name: create dev folder
  file:
    path: "{{ ansible_env['HOME'] }}/dev"
    owner: "{{ ansible_env['USER'] }}"
    mode: '0755'
    state: directory

- name: create virtualenv folder
  file:
    path: "{{ ansible_env['HOME'] }}/dev/virtualenvs"
    owner: "{{ ansible_env['USER'] }}"
    mode: '0755'
    state: directory

- name: brew taps for python2 and python3
  homebrew:
    name:
      - python2
      - python3
      - ipython
    state: present
    update_homebrew: yes
    upgrade_all: yes

- name: brew cask taps for python
  homebrew_cask:
    name:
      - pycharm-ce
    state: present
    update_homebrew: yes

- name: install pip3 virtualenv packages
  pip:
    name:
      - virtualenv
      - virtualenvwrapper
      - pipenv
    executable: pip3
    state: present
