---
  - name: add .ssh dir
    file:
      path: "{{ ansible_env.HOME }}/.ssh"
      state: directory
      mode: 0700

  - name: add new default ssh key
    command: 'ssh-keygen -b 4096 -t rsa -f {{ ansible_env.HOME }}/.ssh/id_rsa -q -N ""'
    args:
      creates: ~/.ssh/id_rsa

  - name: add Ed25519 ssh key
    command: 'ssh-keygen -t Ed25519 -f {{ ansible_env.HOME }}/.ssh/id_ed25519 -q -N ""'
    args:
      creates: ~/.ssh/id_ed25519

  - name: check for existance of rsa key passphrase
    command: 'ssh-keygen -p  -P "" -N "" -f {{ ansible_env.HOME }}/.ssh/id_rsa'
    register: sshkeygen_cmd
    failed_when: sshkeygen_cmd.rc == 0
    changed_when: False

  - name: check for existance of Ed25519 key passphrase
    command: 'ssh-keygen -p  -P "" -N "" -f {{ ansible_env.HOME }}/.ssh/id_ed25519'
    register: sshkeygen_cmd
    failed_when: sshkeygen_cmd.rc == 0
    changed_when: False
